import type { Product } from '../domain/product';

const now = new Date();

export const testProducts: Product[] = [
  {
    id: 'laptop-001',
    name: 'Dell Latitude Laptop',
    description: 'Standard university laptop for coursework and projects.',
    quantity: 15,
    loanDays: 2,
    updatedAt: new Date('2024-01-05T12:00:00Z'),
  },
  {
    id: 'projector-001',
    name: 'Epson Projector',
    description: 'Portable projector for presentations and group work.',
    quantity: 23,
    loanDays: 2,
    updatedAt: new Date('2024-02-12T08:30:00Z'),
  },
  {
    id: 'camera-001',
    name: 'Canon DSLR Camera',
    description: 'Professional camera kit for media students.',
    quantity: 18,
    loanDays: 2,
    updatedAt: new Date('2024-03-20T16:45:00Z'),
  },
  {
    id: 'tablet-001',
    name: 'iPad Pro',
    description: 'Tablet device for digital design and note-taking.',
    quantity: 27,
    loanDays: 2,
    updatedAt: new Date('2024-04-10T09:00:00Z'),
  },
  {
    id: 'mic-001',
    name: 'Audio Recording Kit',
    description: 'Microphone and audio interface for podcasting and recording.',
    quantity: 12,
    loanDays: 2,
    updatedAt: new Date('2024-05-15T14:30:00Z'),
  },
  {
    id: 'hdmi-001',
    name: 'HDMI Cable Pack',
    description: 'Set of various length HDMI cables for presentations.',
    quantity: 30,
    loanDays: 2,
    updatedAt: new Date('2024-06-05T11:15:00Z'),
  },
  {
    id: 'tripod-001',
    name: 'Camera Tripod',
    description: 'Professional tripod for photography and videography.',
    quantity: 14,
    loanDays: 2,
    updatedAt: new Date('2024-06-20T13:45:00Z'),
  },
  {
    id: 'calc-001',
    name: 'Scientific Calculator',
    description: 'Casio FX-991 calculator for math and engineering courses.',
    quantity: 22,
    loanDays: 2,
    updatedAt: new Date('2024-07-08T10:20:00Z'),
  },
  {
    id: 'adapter-001',
    name: 'USB-C Hub Adapter',
    description: 'Multi-port USB-C adapter with HDMI, USB-A, and ethernet.',
    quantity: 19,
    loanDays: 2,
    updatedAt: new Date('2024-07-22T16:00:00Z'),
  },
  {
    id: 'speaker-001',
    name: 'Bluetooth Speaker',
    description: 'Portable bluetooth speaker for presentations and events.',
    quantity: 16,
    loanDays: 2,
    updatedAt: new Date('2024-08-12T09:30:00Z'),
  },
  {
    id: 'whiteboard-001',
    name: 'Portable Whiteboard',
    description: 'Small whiteboard with markers for group study sessions.',
    quantity: 11,
    loanDays: 2,
    updatedAt: new Date('2024-09-01T14:15:00Z'),
  },
];
